1. Thor
2. Tony Stark
3. T'Challa
4. Peter Quill
5. Thanos
6. Nick Fury
7. Doctor Strange
8. Wanda Maximoff
9. Captain America
10. Hank Pym
11. Black Widow
12. Groot
13. Sam Wilson
14. Odin
15. Tyler Hayward
16. Kaecilius